# Generated by Django 4.2 on 2023-04-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('work', models.CharField(default='', max_length=50)),
                ('experience', models.CharField(default='', max_length=50)),
                ('graduation_date', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('blog', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('num', models.CharField(max_length=12)),
                ('desc', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('application_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('fullname', models.CharField(default='', max_length=50)),
                ('fathername', models.CharField(default='', max_length=50)),
                ('mothername', models.CharField(default='', max_length=50)),
                ('ssc', models.CharField(default='', max_length=50)),
                ('inter', models.CharField(default='', max_length=50)),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('address1', models.CharField(default='', max_length=50)),
                ('address2', models.CharField(default='', max_length=50)),
                ('bio', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
            ],
        ),
    ]
